#ifndef _CTRLS_H
#define _CTRLS_H

/* chatlist控件的消息 */
enum CHATLIST_MSG {

	CM_SETVIEWMODE = WM_USER+1,
	CM_GETVIEWMODE,
	CM_ADDGROUP,
	CM_SETGROUP_NAME,
	CM_SETGROUP_NOTE,
	CM_DELGROUP,

	CM_ADDBUDDY,
	CM_SETBUDDY_NAME,
	CM_SETBUDDY_NOTE,
	CM_SETBUDDY_SIGN,
	CM_SETBUDDY_PIC,
	CM_SETBUDDY_STATUS,
	CM_DELBUDDY,

	CM_BLSORT /* 单组好友列表重新排序 */
};

/* 我的按钮控件消息 */
enum {
	CBM_SETRADIUS = WM_USER + 1,
	CBM_SETMARGIN,
	CBM_SETBCOLOR,
	CBM_SETBCOLOR_HOVER,
	CBM_SETBCOLOR_PUSHED,
	CBM_SETFCOLOR,

	CBM_LCLICK,
	CBM_RCLICK
};
#endif
